### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by cwaku** [nevisende/awesome-books#2]
Amazing work you did here. Also congrats on getting approved.
One thing I realized that might need a little improvement in your commit messages. In my opinion, it'd be more helpful for the reviewer if they were more descriptive(eg: "Add logic to add/remove books" instead of "Updated script.js")

**Comment by kingqabil** [comment]
Good Work! you nail it, there is anything to say rather than good job

**Comment by nevisende** [comment]
Thanks for your comments.
