### ISSUE TITLE
Morning peer-peer code review

### ISSUE THREAD

**Issue by cwaku** [nevisende/awesome-books#6]
Awesome work you two did here.
One thing I realised is that the link to your live demo in `README.md` isn't working. Kindly fix that

![Alt Text](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)

**Comment by kingqabil** [comment]
Good job guys, you did it well I would suggest you if you can put all the js in one file it will be greet

**Comment by nevisende** [comment]
Thanks for your advice and comments :)
